### ISSUE TITLE
the training parameter about clip

### ISSUE THREAD

**Issue by longmao-yiran** [Boyiliee/AOD-Net#1]
hello ：
   I am very glad to see your public your model, I have already seen your paper, there is a question to ask you, you mentioned in the paper  “It is also found helpful to clip the gradient to constrain the
norm within [−0.1, 0.1] ”.It means the solve parameter  which called "clip_gradient" is among [-0.1,0.1]

**Comment by Boyiliee** [comment]
Sorry for the late reply, yes it is, and you can find the related work using "clip_gradient" in "Accurate Image Super-Resolution Using Very Deep Convolutional Networks". It is of great importance during training AOD-Net. Hope this helps.

**Comment by longmao-yiran** [comment]
Thank you very much for your answer.
