### ISSUE TITLE
An error occured in code running

### ISSUE THREAD

**Issue by nicholasly** [Boyiliee/AOD-Net#2]
When I tried to run the file `test.py`,  an error occured as folows:

```
Traceback (most recent call last):
  File "test/test.py", line 78, in <module>
    main();
  File "test/test.py", line 74, in main
    test()
  File "test/test.py", line 58, in test
    net.blobs['data'].data[...] = batchdata;
ValueError: could not broadcast input array from shape (3,540,360) into shape (3,600,400)
```

It seemed that the error was caused by the transpose operation in test
`  data = data.transpose((2, 0, 1))`

and the dimension of the image was somehow not adaptive to the code.
But I changed the line 43 in test
  `npstore = caffe.io.load_image('data/img/%s.jpg'% imagename)`
to
 `npstore = caffe.io.load_image('data/img/gugong.jpg')`

The code ran normally. I want to know what led to the error mentioned above. Thank you!

**Comment by YogeshShitole** [comment]
Hi How to train AOD-NET with my own data.. I can see test.py script but train.py is not available I am new to Caffe

**Comment by sachinpuranik99** [comment]
Unfortunately, you will have to create your own training script in order to train the model as I am not the owner of this repo. However, if you are okay with Keras framework have a look at this.

https://github.com/sachinpuranik99/AOD_Net/blob/master/aod_net.ipynb

**Comment by Boyiliee** [comment]
Thanks for your questions, 
1. This code is adaptive to all resolutions, I am not sure why you meet such problems, but you need to keep all materials in the same folder, then you could get the results.
2. For training process, please refer to AOD-Net paper, I have mentioned detailed relevant parameters clearly.

Hope this helps.
