### ISSUE TITLE
Training AOD-NET

### ISSUE THREAD

**Issue by YogeshShitole** [Boyiliee/AOD-Net#3]
@Boyiliee Thanks for sharing your work publicly I went through your paper and wanted to reproduce it ....I want to to train AOD-NET with my own data
I am new to caffe I can see test.py script but there is no train.py can you please help me on how to train AOD-NET, I will really appreciate your help

**Comment by Boyiliee** [comment]
Thanks for your questions, for training process, please refer to AOD-Net paper, I have mentioned detailed relevant parameters clearly.

Hope this helps.
