### ISSUE TITLE
pytorch部分代码好像不完整

### ISSUE THREAD

**Issue by cherry5219** [Boyiliee/AOD-Net#7]
from utils import logger, weight_init
from config import get_config
from data import HazeDataset

这几个代码好像没有提供 运行出错 请问是什么原因呢

**Comment by Boyiliee** [comment]
Here is the unofficial implementation (https://github.com/TheFairBear/PyTorch-Image-Dehazing) of AOD-Net. **Based on this code**, we add simple PONO into AOD-Net, which improves the performance efficiently.

Hope this helps.
